// <auto-generated />
using AJsCleaning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AJsCleaning.Migrations
{
    [DbContext(typeof(AJContext))]
    [Migration("20240409214231_Teams_Update")]
    partial class Teams_Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AJsCleaning.Models.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "- Cleaning floors furniture, windows, walls, restrooms, and other common area surfaces.- Disposing of waste- Vacuuming carpets- Scrubbing toilets- Dusting ceilings, light fixtures, countertops, loose furniture (high and low dusting as well as wet dusting)- Washing and drying windows (including window sills and frames)- Carrying out heavy cleansing tasks and special projects (deep cleaning fridges, washers, dishwashers, etc.)- Notifying clients of occurring deficiencies or needs for repairs.",
                            Service = "Deep Cleaning",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Providing organizational services to help clients declutter and optimize their spaces.",
                            Service = "Organization",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Regular cleaning services, including dusting, vacuuming, mopping, and general maintenance of spaces.",
                            Service = "Normal Cleaning",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cleaning services specifically designed for moving in or out of a residence or commercial space.",
                            Service = "Move-in/Move-out",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cleaning services before or after construction projects, including dust and debris removal.",
                            Service = "New & Post Construction Clean-Up",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cleaning and arranging spaces to enhance their appeal for potential buyers or tenants.",
                            Service = "Real Estate Staging",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Specialized cleaning for households expecting or with a new baby, focusing on a hygienic and safe environment.",
                            Service = "Newborn Arrival Cleaning",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Cleaning services tailored for short-term rental properties, ensuring cleanliness for incoming guests.",
                            Service = "AirBnb's & Vacation Rentals",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cleaning services for commercial office spaces, including desks, common areas, and janitorial tasks.",
                            Service = "Office Cleaning",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Cleaning services for commercial office spaces, including desks, common areas, and janitorial tasks.",
                            Service = "Gardening",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Basic pet care services, including feeding, walking, and other routine tasks for pet owners.",
                            Service = "Pet Care",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Assisting clients with grocery shopping services.",
                            Service = "Grocery Shopping",
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Providing laundry services for clients, including washing, drying, and folding clothes.",
                            Service = "Laundry Services",
                            Type = 2
                        });
                });

            modelBuilder.Entity("AJsCleaning.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hi, I'm Janelle Fineout, busy mother of four, who needed more flexibility for my children when COVID hit back in 2020. With many years of cleaning experience already, I decided to open up a cleaning business with a coworker I had taught children with for 7 years. At the time some thought we were crazy, opening a business during covid, but as I saw it, sanitation was booming and took it as a business opportunity. Within 6 months, we were working full-time, expanding, providing dependable, top quality cleaning services for residential and commercial clients in the Grand Traverse County area. Our Team loves to organize and clean your space, giving customers their time back, while we handle the details.",
                            Name = "Janelle Fineout",
                            PhotoPath = "/images/teams/Team-Janelle.jpg",
                            Title = "Owner"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hey there! I’m so loudly and proudly the A in AJ’s, Alyssah Fearnow! Commonly known as Lys. \r\n\r\nI am a wife to my amazing and supportive husband OB and momma to our spunky fur son, Meatloaf who brings endless joy, an abundance of snuggles, so much hair and tons of mud to our household. He is reputable for nose boop marks on all of our windows! \r\n\r\nI possess a strong drive, unwavering determination, and a firm self-assurance as a determined and driven female professional. I also possess a strong drive to have way too many plants, pet every dog I meet (after asking), eating all of the good food, and watching all of the junk tv. I found someone who shares some loves of mine, side by side with the J to my A for the past 7 years we became known as the dynamic duo! \r\n\r\nLetting A&J's have your back with all of your cleaning, sanitizing, disinfecting, organizational requirements, and dog petting, whether for residential or commercial settings, will prove to be the “BEST” choice! Big or small, we clean them all!",
                            Name = "Alyssah Fearnow",
                            PhotoPath = "/images/teams/Team-Alyssah.jpg",
                            Title = "Owner"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hi, my name is Danielle Franks and i am a loving mother to 3 beautiful children. At the age of 14, my first job was working in hotels, and I've had almost 10 years of cleaning experience . I took some time off during covid to raise my youngest and have since been with A.J.s for almost two years. It is so important to me to have a good relationship with the people that I work with and have found that with this company. I also enjoy getting to know our clients and their families, and I love pets of all kinds. It is a joy to come to work every day, and I find great satisfaction in a job well done.",
                            Name = "Danielle Franks",
                            PhotoPath = "/images/teams/teams_danielle.jpg",
                            Title = "Employee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
